### ISSUE TITLE
Item cheats don't work

### ISSUE THREAD

**Issue by levontiy-glass** [K3nny567/Cheat-Menu-Framework#5]
![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/125562588/83d6f095-17c3-4708-b203-f1b027144eeb)
When trying to use Item, Armor or Weapon cheat game crashes, V.0.8.8.3

**Comment by K3nny567** [comment]
This has already been fixed in the version here on github.

The version hosted on MEGA as linked on the F95 post will be updated once we reach v1.0

There is a fix for the F95 version for game versions after v0.8.8.0 in the description for Inventory Editor in the addons section of the mod post.

![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/144315629/694c0261-2e81-493b-a071-b0feccd16fdf)
![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/144315629/7574c3d8-41e9-4ff8-82c9-4ef398bc230f)
