### ISSUE TITLE
How fix this  shit

### ISSUE THREAD

**Issue by Parumi-system-administrator** [K3nny567/Cheat-Menu-Framework#9]

**Comment by K3nny567** [comment]
Need more information

- game version (Must be 0.8.7.4 or above, readme has been updated to reflect this)
- mod version
- errorlog

**Comment by 96flo** [comment]
Alright dude all that you need to do is just go to \LonaRpg\ModScripts\_Mods\Cheat-Menu-Framework\Framework\scripts
Delete all code that he had and paste

I trough that will help to you

```
##---------------------------------------------------------------------------
## CheatUtils Module
##---------------------------------------------------------------------------
module CheatUtils
  #Check if a game is loaded
  def self.ingame?
    return (!SceneManager.scene_is?(Scene_MapTitle) and !SceneManager.scene_is?(Scene_AdultContentWarning) and !SceneManager.scene_is?(Scene_Title) and !SceneManager.scene_is?(Scene_TitleOptions) and !SceneManager.scene_is?(Scene_TitleOptInputMenu) and !SceneManager.scene_is?(Scene_ACHlistMenu) and !SceneManager.scene_is?(Scene_Credits) and !SceneManager.scene_is?(Scene_Load) and $loading_screen.disposed?)
  end
end

```

**Comment by K3nny567** [comment]
> Alright dude all that you need to do is just go to \LonaRpg\ModScripts_Mods\Cheat-Menu-Framework\Framework\scripts Delete all code that he had and paste
> 
> I trough that will help to you
> 
> ```
> ##---------------------------------------------------------------------------
> ## CheatUtils Module
> ##---------------------------------------------------------------------------
> module CheatUtils
>   #Check if a game is loaded
>   def self.ingame?
>     return (!SceneManager.scene_is?(Scene_MapTitle) and !SceneManager.scene_is?(Scene_AdultContentWarning) and !SceneManager.scene_is?(Scene_Title) and !SceneManager.scene_is?(Scene_TitleOptions) and !SceneManager.scene_is?(Scene_TitleOptInputMenu) and !SceneManager.scene_is?(Scene_ACHlistMenu) and !SceneManager.scene_is?(Scene_Credits) and !SceneManager.scene_is?(Scene_Load) and $loading_screen.disposed?)
>   end
> end
> ```

That's wrong. That would allow the menu to work during the first time setup which is a really bad idea as the language has not been set yet.

Also, I would hope that path is not how you have the mod installed because even with UMM it would not work. The mod should NEVER be installed by cloning the repo into a local repo (method used doesn't matter) in the _Mods folder as the file/folder structure is for feature separation during development (and no longer has the translations in this repo)
Only use the downloads attached to the releases.

The correct code change for older game versions is on the F95 post for the mod in the compatibility section.
